# Generated by Django 5.1.7 on 2025-03-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("visitor", "0003_alter_visitor_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "pass_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("limited", "Limited"),
                            ("NA", "Not Applicable"),
                        ],
                        default="NA",
                        max_length=7,
                    ),
                ),
                ("validity", models.DateTimeField(blank=True, null=True)),
                ("pass_image", models.TextField(blank=True, null=True)),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passes",
                        to="visitor.visitor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
