# Generated by Django 5.1.7 on 2025-03-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=10)),
                ("address", models.TextField()),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "visitor_type",
                    models.CharField(
                        choices=[
                            ("civilian", "Civilian"),
                            ("internal", "Internal"),
                            ("gov agency", "Gov Agency"),
                        ],
                        default="civilian",
                        max_length=20,
                    ),
                ),
                ("gov_id_type", models.CharField(max_length=50)),
                ("gov_id_no", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="visitor_images/"
                    ),
                ),
            ],
        ),
    ]
