# Generated by Django 5.1.7 on 2025-03-26 02:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visitor",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="phone",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
