# Generated by Django 5.1.7 on 2025-03-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitor", "0002_visitor_created_on_visitor_updated_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
