# Generated by Django 5.1.7 on 2025-04-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitor", "0003_alter_visitor_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="visitor_type",
            field=models.CharField(
                choices=[
                    ("civilian", "Civilian"),
                    ("internal", "Internal"),
                    ("foreigner", "Foreigner"),
                    ("gov agency", "Gov Agency"),
                ],
                default="civilian",
                max_length=20,
            ),
        ),
    ]
